#! /usr/bin/env python2.7

from fabric.api import *
from fabric.utils import *
import argparse
import socket

dom0 = 'husky0.dtg.cl.cam.ac.uk'

env.user = "root"

@hosts(dom0)
def find_vm_ip(name):
    """
    Find the IP address for an existing VM.
    """

    vm_uuid = run("xe vm-list params=uuid name-label=%s --minimal" % name)
    if not vm_uuid:
        abort("No such vm: %s" % name)
    vm_interfaces = run('xe vif-list vm-uuid=%s --minimal' % vm_uuid)
    if not vm_interfaces:
        abort("No network interfaces found for %s" % (name))
    vm_ip = run("xe vm-param-get param-name=networks uuid=%s param-key=0/ip" % vm_uuid)
    return vm_ip

if __name__ == '__main__':
    output['running'] = False
    output['stdout'] = False

    parser = argparse.ArgumentParser(description='Find the DNS name for a VM')

    parser.add_argument('name', help='The name of the VM')

    parsed_args = vars(parser.parse_args())
    vm_ip = execute(find_vm_ip, **parsed_args)[dom0]
    print(socket.gethostbyaddr(vm_ip)[0])
